import { investmentGraph } from '../agent/graph.js';
import fs from 'fs';
import path from 'path';

const TICKERS = ['TSLA', 'AAPL', 'NVDA'];

async function runGraphForTicker(ticker) {
  console.log(`\n=========================================`);
  console.log(`Running LangGraph for ticker: ${ticker}`);
  console.log(`=========================================`);
  
  const stream = await investmentGraph.stream(
    { ticker },
    { streamMode: 'updates' }
  );

  const cumulativeState = { ticker };

  for await (const chunk of stream) {
    const nodeName = Object.keys(chunk)[0];
    const nodeState = chunk[nodeName];
    console.log(`  Node finished: [${nodeName}]`);
    Object.assign(cumulativeState, nodeState);
  }

  const data = {
    profile: cumulativeState.rawData?.profile || {},
    quote: cumulativeState.rawData?.quote || {},
    analystTargets: cumulativeState.rawData?.analystTargets || {},
    historical: cumulativeState.rawData?.historical || {},
    gateway: cumulativeState.gatewayStatus || {},
    dataConfidence: cumulativeState.gatewayStatus?.dataConfidence || 'HIGH',
    dataProvenance: cumulativeState.gatewayStatus?.dataProvenance || [],
    metrics: cumulativeState.metrics || {},
    percentiles: cumulativeState.percentiles || {},
    anomalies: cumulativeState.anomalies || [],
    macro: cumulativeState.macroAnalysis || {},
    frameworkSignals: cumulativeState.frameworkSignals || {},
    validationLogs: cumulativeState.validationLogs || {},
    debate: cumulativeState.debate || {},
    verdict: cumulativeState.verdict || {},
    report: cumulativeState.report || {}
  };

  return {
    id: `seed-report-${ticker.toLowerCase()}-1`,
    ticker: ticker,
    companyName: data.profile.name || ticker,
    sector: data.profile.sector || 'Unknown',
    verdict: data.verdict.decision || 'HOLD',
    score: data.verdict.score || 0.0,
    label: data.verdict.label || 'HOLD',
    createdAt: new Date().toISOString(),
    fullPayload: data
  };
}

async function main() {
  const reports = [];
  
  for (const ticker of TICKERS) {
    try {
      const report = await runGraphForTicker(ticker);
      reports.push(report);
      
      // Delay to respect Gemini API rate limits
      console.log('Staggering 5 seconds before next ticker...');
      await new Promise(resolve => setTimeout(resolve, 5000));
    } catch (err) {
      console.error(`Error running graph for ${ticker}:`, err);
    }
  }

  const fileContent = `// Autogenerated seed reports for Quorum Client-Side Storage
export const sampleReports = ${JSON.stringify(reports, null, 2)};
`;

  const outputPath = path.resolve('lib/storage/sampleReports.js');
  fs.writeFileSync(outputPath, fileContent, 'utf8');
  console.log(`\nSuccessfully wrote ${reports.length} reports to ${outputPath}`);
}

main().catch(console.error);
